unit TestDomain.Model;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, Domain.Model.Cargo, Domain.Shared;

type
  // Test methods for class TrackingId

  TestTrackingId = class(TTestCase)
  published
    procedure TestConstructor;
  end;

implementation

{ TestTrackingId }

procedure TestTrackingId.TestConstructor;
var
  ATrackingId: TrackingId;
begin
  try
    ATrackingId := TrackingId.create('');
    fail('Should not accept null constructor arguments');
  except

  end;

end;

initialization

// Register any test cases with the test runner
RegisterTest(TestTrackingId.Suite);

end.
